---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBUiECHrCfbwv+CEFqZhZmdGF5T7E+Q6W8qJxnGY6uq9GTzA7ddeqsvVcBiO4/x8kh+Je1g6eZLlslwfOpSC4wBwATFKpaDrFPWa0hIWV753jH5NRC8/mrpOr6rkjsEuykGX+YDOcCc8ej1iSxd4s10e79skqYvlTMfXbSQf3hTOPZBmKE5zy1CHF4iHCKzL8bnglJxuSqjzlmW1JsFvkcwg4kRQdL5KbZHzF2mJHAbIxO3z/NBPo4RG2M9aLrdaZ+26r4m65P61jjRvYJFwJcOtpje30+hfh3qsRXUTTF4X3UAiTU3SkQAIk49EeGqKl6mcYvPo7xfcaAbWIGZGQY4vDtTCQEE5EE31uuPtYL6p8/5QwtbifREgP82pddpg+RibKMoPQHOxS3I3dB1M0wUEjKAXYc3utW3lSyw5XXYltg2SnoRlXRCs/9gw94X4GZ8xC0m9koPb/h4zNu3dEh4FBu1j+nose7sfrQbKTRnT2m2nkfFdFqY8OWOVd8z08L8RjsyDYWhyd9SiVVSmy0wKhLTey8pjEUQpKqEQDpPjZLETAqFNNGs2BJaT0DF//bocQkYsbAjOJgFos+MASOwzeahkr+GCLPeKV9nVpgG1ISIA8tkxYrnnPM/D6eYFv0h8LkXUW9humngxZpIJL3ho29j0Lgcb8ltLxmxqE/kIn4GlRMWrZFpg17HnYDOC4yCtByV+3fb6VYdEU9Hk8Cp0QM=
    admin-user: AgAVne1IKFzDZv6gvpaRwjCmCjrYlz5GugfEvg6Fmt4d1HHNoFR0I9QtHpjTJB2cHlPFt6jffh+W6RuEht5Nf0D0hrHsTh1gw3cyIxOW+20BrnIK5lUKqUxQlLyAIx+RwJWwYYbVOhDk/yLG+0SSebrpvLJXhh139JQUaEC3ftNYY+BcE1VvaXD76ph98hPyVU1B3/UHB+jtKHo9ZHQrLPetN39jhwOc53JMJpJ5RA6VdZ2f0OXOaUSo0DCsEUL2uoavTO07Pc5k/ivpUWFaxbOyhdSZttVpSwxB15W7MR/cpaWutXMkzUmDEPj7xvXXcGSnHyW6Ju/HrPXkSkMoomcKFKhuu1tukvDfCXhpzW5fKgSH1dal5/B6FVKmMfUxkOe5lCenDOamgHYWGcYWJj9dhhiM5Fluzn5TmK5rRP8K8fCYbHg/d/rwjxrN4ZQTqa33IlDe5GusQFKKubgtP01dwS9wgD1nBydD/lXDqL2uTIGcmP3dJB6JnAwv79fJAWp6fZSO1+eQgqhRxcDN4dETL2CCyG9iN9tbrCy645DM4LyZVgXA/OPSiK3QihYFXh+j5SnlABRYzRTISC8eA9op6L8RUGChlBMCqQpKzukF6oR3C5lKBks7YnX3SB8nYYnOtZE9gGSOpvrwttcjFt4irJHgfZiUs3LqX2P1yAHDS1B+B3g856g40CqqCTxUFolOwRg2KQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
