---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-service-db
  namespace: data
spec:
  encryptedData:
    password: AgA2hW/Gq/VI7QapDoNUT457/0joZL43KAeUtBeO7YCcbxYLROKB0cP2Be5+HqU8QzNv1eL/k9MjbIcRP+fpCHhObzjZn7zvYY+FtvhaI96cKpkdKev53JFY7Km7xROijGuW1MEaFiK3Z7DsVWhVik25wLT7ddyIH+yk2RYlG17ohHQM+vepCN3ID4qwE9VquW7M/DBkie4W8OARBPzViWMb07FqTBBIb3+xF1soQ3olh4TYnfuKWEIFo5wCoSKh/hGSmQbM8uCx4WoFDWobUiEBJ0WYtCB2FjPV3pbGWh8Q9tEl+X1RpRZejfbnXAlycUrqyxwDv+nCxGXPdufKafFn8WA5kYrCjBok85/FNb9KfvAvHN2FTHOn+bGW/M6w0nSps1fKQF6o6dvTn6tmDa3PR7BBkC+xqY6IwKd4vj57W50R4ctquUhwMScA3x0MfeBilRnKSBt11vc1eU+K5zy3dQoduITYlRcFh/tOdrgLTTrqgiFS8ZEf1dGu+BJacWQuj8eJeZiNBklFpK9jXROHeCGiVCy9eHutG1hNQS+7BDAn/gsNDsIlLnZJJe47+IE3HTjCcHWTHy7pIMz4WIDudP9XAdsbot+CEsMzFRVBAeXZHKjm4XKdNSOPYx0QpnigdKPsrt6IZ6rBnTo6NdP/rM4MU+cwLiRq8SivlRe3BqV8GBarAQ0Y9hThU9pkP1Gr7KSnUiURJomWs6EZb+EB9JojJqK9Ojy4AR9gpvcxsQ==
    username: AgCRYuKuDIu2lxHr58vNjREwX/XyCf2vD+D5jM8+3tkyeplt8KSqS+O7z7Wxe7e0YEUOZ+k5Y51/owP8GgRxCtHM9sj94ukoVYML1KDDrM1JpeDxpWAhy+a+Au1UWqRVWKMb5GTIWf4OfowP3IRNsTmZXKj8gitRKTFLGv9Y5Z0YvQobHZwZ7f5GSgjsnQo6ue7QqerbnjFcitsRzSZUsoq+mHSAAjXSWjUQBV6vawbUhd6hArxXcHJ2MM/ndAypp7inv7kevjmCk3aJqlxPlnZMUtV4BuO/uQXajCfSLRVzskdImb09p2tUC7p+lejtHrlWo4jAQu9s5V3z6kyqEe9TgVzdLXL66gGuuOr8vL+Mfjr/juvrh/oolYS1LATWr/Gm+rzRk12GUOSzOOXA2VKouAVF8ARtQ+lmtHQsjdgusY+3laBWhC5kKaXqCkaaNM4LbOvLL2oB+PxDZI5P9VAE84lq9VQ8Itco5L14Q54bQb/JX2H6K20nzO+59csVyyeq9ZL+4etamR+m+R9N6teBt/T7QCYnQEBusAAHp0vSpbadVSvRlQCx7Dj7HxRXHi4gH16Bb27lo6wIj9ltYVApXzxgHyl6wCh4N4jgEtV0hyvvpwAJ+Ah6jB7n/Do8JHhWmHGVHab9U64ct63UBbvR3wYnEiLYAkBQHZClhXsvv42gUq9Vo+v8PpGpyIv3AanWIkF0WZJy
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: data-service-db
      namespace: data
    type: kubernetes.io/basic-auth
