---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-db
  namespace: data
spec:
  encryptedData:
    READ_PASSWORD: AgBEdJx/tTEYoMg/mVA1B7Hbxhb4VC13XAL8mCaiVKN3Ek8jvC89FgVH8IRsuuye0Z+2VGgMPUrDQ3yxCmifSN9KJWssN0Yyns+BBXc62KGwIP4si/8lwjcswuZHJvzB9AonaZSOnu3Dwr0KIFY8jVNCyOzYEIi/UrhQgzT65WebveX1uRpQPvTmmC2PWShrheKQcEuPL2BQ5natn7FRQYT8oBBWj2etSKqczIXTbFocX2WNLOSajgkYVxcbnArPoaNeFMaLGMwZC2VeAy6iS+WIQdZ4lnZ+UiyDY2/Hq41WRbILLDJ+AD8gD6ktv4/ByG6Na9emTESzK9izk4Fzxz51Tk58ptvW/duQy7ljgGFS7AxOHjCE0vxFm6XWQsQ6pFSzWqMx/dbYblOO6CcUAOj62Q8mC350UxmI7Ny1EktdTS3Mos7W8UzBIn7oSmakV6K1tg+4eq0jdTsUklFyM6hhKHHPWVNQolSYCfWwq6I+QwSZpdQIX7O/0fffzm/ApI8tjWlxLkTQCjQ353ZbOcnV3TosII1Xx+Az4kycf3dmHQDNix0lz4ZkbrZPs1VLn2t+xztP42R7tXCiNdZmeizwvcoEqjGIh35ETlThJLmkDtmktPlcNEXSNbqIE4nCJcjHU0HBy2rJgzzzf1toBIMySYGlSabaMJm5AB1SgTotSECHCErubTdpEwi3AkInJwiJVQ8cMVbT0kM=
    READ_USER: AgAgkYhSWjngBr9/XZsEGkFPBaKuIrLOSuAfZkZjv9ts/M14nurnlgfpXb1WUTjOo8J0gnBDInwNpgxBU43p0llTb37Hci1HJj/TEx4TfZowPkBXSeM24dU/FSxNjJE52E2PBe1mt7ZwXRopeSRxaSiVehPYBdUJdi/ZVVZmT7w31iWF4VeYbKU2cieZWHBS1WBXPgCOJ4VldILRVYM9cnzTWpQJ4/MKWz07M19bzGqsqM/k7F2JrVtG/ErF2/NUXrWTPiFJpclcgC1dFoU3PEWlJ6iWWdJKmCqDzgxJCA1Kdm4kQT7jorbYcru4BIt7F7eY59x7zFdbkITPvySfiFLW6w17pOJEUQbD9dCzM7oIAPGpL6RmJaw0xivcewQp7FzFvyV49DRIylpGUX84sjyhaRr7ADtQYNSjWc5l+lfu12X8r1tML3w5cx199NctNoNOQV8C0rgujLmcYjhNQUnHlCYurLjrs+FwDwtLMbbW+86ct2aG1/DJynEjiCv/ardUME8aLfauxAe3h6guIfoueB3FL8C2yaiJlvugbufMJmMbd08ukG+CaKGdCNEbAm2oeloWDLg4nBKf1Fx1Uo+0puLci/WPR7td6fgFk2H//sNGXVmD7hNvrok/G2MAGyMtUWoAYRslTBdgEdz1DzOj1hFvIAdrch8lKjkE/h+6xrU6aCxyuf9zH1VJj1QS64EmVGKM
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: external-db
      namespace: data
    type: Opaque
