---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-app
  namespace: data
spec:
  encryptedData:
    password: AgC8zQuOrPm5YjHurjGrLt+FeT8VAuVX4pTCED7/ZsnMXbIN2WggXE2FUG2DZe1BOjC1UEBmskpBzGHg8m2DkWGAgxU8mioXFcB3+X7W4TxtsqBpVEmmAXKIcP3WFD6fU0A70GOX0h2Tjrki2c2JRLY6h/if1YhAHd0KaxlNtBd+9eIdJ1O1n7B1obW+3D+1WJ4jdjyhDIlUYMC4IEkxJag6pFN809BwhmM2s5bs8rTZI9C5LpriBPsJgXSdQLjjrz1TIXG6l2STNy/kp44wGe8EdoErxlI6EbdPcu1Kf4tiyqPuY8g+iHRNSz2Jvmq03G71CLUrztwP0468/a+q4vH/qAbg75/wdWnbNYf1PEaHZLR/Ie/I4Jkt+9CQw64vmAeSy6snJg9DcgBjcJhuqZn0AOt8QMqK7L2nn+xX1hMrPi/dsmh+O6n9AKQKKLzy/5yshqyt/MQB0Rs7Q0jCIpbrOZvKDPt/Hmh1txxmrFM0LwfM916FRaJaC93pn3gJne5z0PuYUzBgLYt6eaE6dSuQcxFeEl1V/fJwtYL/oJwVnaI20H/KmO8+wH8lc+hlXqU1iInEtTe6FQcYupDo1d7O8j/mny4fHIx2osU8scWWtcbF0D5rSdzZpJVXAnjM7aTKzzC6vau6Ya+tYsYIw+ZjaIX8Seiqy+SfxK3sjc+I009C0sofJuNliImt0ptlF1tpqp8cBim6EiwZFLdpJNTeqCw=
    username: AgBSt9ZsmALet9DNE4eVktElhWIS40Yn5CzN3D/SMzf8n2Lbq2D/7420Xbs6dM2r4fam1D7hBa/+/EOAAOhJDEzqJVj6OHF1X+1kwxNJhNuTGxjIRlb39+x5dzlrnxJW/42hw/0iFBoyihHe2Ii9/EMJAR3B3pC8p2IRmDnF/a6jmFRrMdb4oj6WpOaAdcXBeP2VdVutnZMJQrVUXNY9PHYASCJ7nmuFfuk+94HU3FdrHlY3EGAuOvCR4GZHS18By9tfzpkAcSfbrON1R2a0EEpUpoTygUmfKEwRgMpL+vIpKXW7WqjxVOIny08MHS9/5h4R78bmvmNx8WxSkS6Vd8iUCFPfwoV3I9EsTp35MLCDK8lsRTo2Wy689la+w4ru4KJf4vCw058HaxrUsDnMdx0cc7FzjheqsnKUaQQIld4DmE92kw8R1BwgdzX9cB3P8W//NyQw7COn7a/Kup2IpQNgmnCSA9skjyWLyaj4ownIGGOJt/8UFJLTAnKz1wuK7bp2SNMTxSOOKCAQKtHmovK/t1gNG/a0h1YrBgapTv4rdoCJW82nNQtK53NOj3CvS09qSz+Qfpw91zDAU/8FYBsQqOF7TMGoHCZrqO8QoCCfZOGEHS53RZFhNv7tpIi/vq/eSB+XxkI5ySAFQDlMKEKmduJ/vIBL05ngk8wyqklb3UbD/pUADtHWEAfTTg/ciM+O0y0oKXnYFWLc9zy9
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: auth
      name: keycloak-db-app
      namespace: data
    type: kubernetes.io/basic-auth
