---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-demo-password
  namespace: data
spec:
  encryptedData:
    password: AgBAySVV825Lv0jYXmSkq1RgOUKAGTb9cFFKnirHltXHK+ZslDCWswAbRK7clnRb9FVEenYMDHenbu69QAlDX5KLBGAyqStrGTtokGfHVXAUi/Lrl2lDIVhV1DBvuskhuErqxA4KyfeCruln0vpEui6NdjQF+X7EqTFhtrTCycW7w76rpOveDvjwMr4vFQbXM0iQj4Kqfr2bLR90dzMmCMwyLtbq/vAfRVPP+3RZdB6AYm9m/J61Q55Udq1imJ4j05Hr9p6kJBwUR0gAHkwJpglZ4ZwMxHuoHEfoBlRbkmIgGmGN9C+T7got+3syQHtvz7KfMGvqri6Tt1HaRNTvFrDgSS5bcys/wAbGIbC54V5yEwUAU5OAvQHsxw6LS10NLxzyj0+2UmwZqLgxHmaIHdQdJjsHsguahNMJcvHdAzY6ZUnGLrtdiXJRL0wh2UODX23nXo8layQUsFEqbPH2e8Yf/oz2RHfeyIiv7wWYjxF44FFI3VJwBlPigUQuZId6Mm4x84G2poQGw9XP79vODENppgHDPtdO5odgwOULe//Kj2Bceh4+Ro28J7EJC5U9PlfPQ+4lDeC1iSOoupOrFtgql0KptELZ6YmsvoobEfYZ1YDb3Ds3SaG5UDvwnaPJqVW1gaSskCwPrFumxJfCaKFuiHgDsKNhptU100r9y4jvEwiu9MjQFzlZMf0tcE2Vp929nUxuaRfmqiDSj0loGiVgvHE=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: data
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: data
      name: mongo-demo-password
      namespace: data
    type: kubernetes.io/basic-auth
