---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-app
  namespace: data
spec:
  encryptedData:
    WRITABLE_PASSWORD: AgCtnlk4MLDhBkNMM2IJV4tB8e0FZDOcXO/2W4S4vaLHeOm+KFmwZQnN6Cram4t255A20IgzMawoP86tLCuY1l1n6a6BaEyfBjYI4UtNHQOXUDE/S5N24NOquOyM+bt7/cg6njozjsg1ASTXD7GiFbuUF9VwDFIkryaEFmy+UqrWCyI0/UxjylYQJtfPRC9+r6Us+lPB5O34vzS3meC9x8Y7svf4HiUP5FEoqgCmFOMETdPv9jt8cfTr02AbsMWirR14tb6erUO23++oRw5NMHO4vFnVZsLmupI4MAmyuo3nDVICkSwwu+yhTSKS1QlTcwCooKuH1Z/YJgpw0q36vETe3UojGrz2TjQB7l5mbXF0SmxAPXvr6c9H7BzgaINVl/emkL6hOQIqz63Oyqnp3H3nQeS+M2gWhaWpFqG7AOFqwryhsO+wMtpqPernffAK/ttkbR3lm3vxeK4/vL8ivgCFsP1ouHCqAsUstTkjZL+cWHNHHb6c6aSvWgpLaW3f+JNQ3KNVrwLmYK6B1C3ujUnCBd0LDRLgtdgLUZ4WrLwzWQkQkaY5FIvc/F3sWwAh6R42FBISXXF/MIebQ7cxPj3VKDG2zRaqNDnjRfcKnIk46VinWRRZq60NtY6MlD4BStWUdP0UuBYLgKkTDzHF0GjYG7QqH0yPphJ5x1QafHK7Z1JUZB6mPDHB4TKjaqupbm/Q618t
    WRITABLE_USER: AgB+3gRL09N2lhVp40l/1c6zZYdOIdjLqtzP31DIkMP/Ca2cUxc0IOapo71NYhkgcCIt3EV6Lh27jfPVerapVeGqOZP21QiC+9WfSXifOJb7IrADhrkmXbCcIaWKZOp3HxMHrlQQLBBR8ELelf5MUbTD3vrdj5PLEAPJHyZ67JvP/fT3EH+SenNkNT2mYWe0AOjoBbUAuP1OowyKJbotnueraqgra5KbDCvE8YnlBju4YXu02DE1eLFbYKRFUtK2COsZDS6pslrVRAX+HHSXSbOY7t9GbedT6aY9qpLRtsYVHCxO1ZzTgiYP8aDr++RbHCdv75oYWKhG7r4x+GTBkyxzv4BL/ek/6+mImBTfH6QLjdMv6QsK99wkiFBqxt2JpPDgPaxUs2lqeqIbNrmizEYfzTEFLvh0CjQ3q5zLEBpoJ7g2dgZlRZR07b7OX5+0Je8Nb+Lq/gPFaNjCkrKpb4dz2IwUr9ZzgnDx6XC39QCoKPVW7vfiGNetqE1FdevWAw0zMoNYOlbcp0YkdVBVANcf95f1DM/7iTMaMwdh3tOq/yQ5CkKMXJ8KPdm3yrpw4jSFwmixQzGlz2jrj0lzdZJt8f5GzTB1UX5+7zvy5rQTNFc0ud3YaFX5dW/tt/zIQ2L23u/fV5DzN5jPGUFU9L4a94iEzCAfl6QGPOWJdX0OXBltOaLo8jYRXfrbH6XPMZ96RbbH
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: business
      name: mysql-app
      namespace: data
    type: Opaque
