apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: default
  namespace: monitoring
  labels:
    alertmanagerConfig: default
spec:
  route:
    receiver: slack
    groupBy: ["alertname", "namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      # Ruta dedicata pentru alerta de temperatura
      - matchers:
          - name: alertname
            value: CPUTemperatureHigh
        receiver: slack
        groupWait: 0s
        repeatInterval: 10m # Trimite la fiecare 10 minute

      # Ruta pentru alerte critice
      - matchers:
          - name: severity
            value: critical
        receiver: slack
        groupWait: 0s
        repeatInterval: 1h

  receivers:
    - name: slack
      slackConfigs:
        - apiURL:
            name: slack-webhook
            key: url
          title: '{{ template "slack.default.title" . }}'
          text: |-
            {{ range .Alerts }}
            *Alertă:* {{ .Annotations.summary }}
            *Detalii:* {{ .Annotations.description }}
            {{ end }}
          sendResolved: true