apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: slack-test-alert
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: slack-test
      rules:
        - alert: SlackTestAlert
          expr: vector(1)
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Slack test alert"
            description: "Test alert for Alertmanager Slack notifications."
        # 2. Alerta pentru temperatura de peste 75°C
        - alert: CPUTemperatureHigh
          expr: max(node_hwmon_temp_celsius) by (instance) > 75
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "⚠️ Temperatură Ridicată CPU: {{ $labels.instance }}"
            description: "Temperatura procesorului pe nodul *{{ $labels.instance }}* a depășit pragul critic și este de *{{ $value | printf \"%.1f\" }}°C*."