---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-keycloak
  namespace: business
spec:
  encryptedData:
    client-secret: AgBhcvsHHpTopxwLG6d5NLkX62XJFhQnue2tQZ8anpd2NlSg6KmkT62k74P74NBaZlq79elvMyX/EcjG1x0oYDOO0p+LCCEOGPiaBIJkcP7Nwu0PgHMGUlsWyxQT/VQ2ZJHQe/UjH7NSDXQS8CgrrhJoGN24KghosPIjcMQWhmRHja8Z1HYcTlX6FxITmI2Xh/rlybNxAiUpTnoTvSL4xtj/kaKcFGERUy4GLr2ltSwltYBuKlapncka92FMr9OpS0tPUINC+y//X5ESJig/hf2w2xAjjh6mat/aq4h7qjtrSHZFtH1AuySCVuFJ+nMpTu6GokM6HHM2lcZJgmO/l+wheWan7JfKIEwPQPEQZTviqdJ0WnbwJTUqoTCja8W/LG+iw4ascmHeWRKgm0k3P/D8syguWrv/nkj5eY948q+QtdVbwvwCOdEHTLUwJxpv7Sp5f6c5mgHo0D0Qe28fXZJ3Kgsq2AANiuNHckVLjfMy8e55cCGGv6k0tCkEq9C6tj+3/l9Qlroi1KsQJjXJmsZToU0gUvYWJlxhBk3Xi/rVbNahxXlWZtSfiT80MqWwSc2sieOBQdNxrLTxOmCIGHKeAxiCU5m3gV2HWhwbd3qWu9sHnsnkyab5+2IxGtaBOG8/qYrZsZ+X/XSC9G/ltb0HHY3QNnlO4EvVat8xQjv6BOwaGydWdo4oLXLLgjs2ydy0yU/dWd3BzY0bQrlSzovzry+HStfVgbTVaPmmzgPl8uSzAlXzw7ZrplRCW0qK
    cookie-secret: AgARbVT5LSZqQ1yi7ksTU+jbFC1J2QDTMWB4IdBO0OiGzZbQ5zYgT+l346+k+bqOOmdWayDk6C+xcUlMP8jrb792WPN3VVJa89ayV4JpdbX0wi28BIH7se1BgluHTtc/qqefjj6FOygtXTXQ5TsZ4wH2z7PuwbM5KDoqL4B1WrYjgtvPB9K+uHU6P9GNXUcuHqiYkec7UqKwXDDePdoHE8oZAKbjhahgpyyOBBjKTdVvbbmdEll6CubON9gMiHW4T6rpEZN6N5bxbCYS66cLGxrIsYYou8Oo0cVHcdrd4C9/3veG3bjyMZ0c8v6uxsxfxxQrN2l7Uwm9fcZ+KdtWb98Fma1ZOl4xehdxya2x3nT4fyQZ4/Kd9JTG0z3y0viqNMiHpk7ocMkofCMloY8bsnM4DhuPIaVUQGw/kZdiJQMNjKn/HXCjtBTNnCRLzo2SC9Sn/eEyBOLQlbnX993a9gsH1zN9yj31tZko0XargbqYay+p9Odlq7nkNdeWnNa92FFLfyCZ+um6STAUoOqrBi6ASOqpRbDkEmHPHlEpZa+vGUN4Nl5jOQhE77/gZ/GiPtEjh8++zpKApJ2Vny0eNr8xZe9taotPQJWQ7LuUlzJFZJilCtabUH75JFsajI9EpVp8L0EKnTan34OHpvk0bKWyrx62qu4entnxjCxbbnprqhuB0cc9z3cBABSikxSp5lKTOEU3PQSNZ6JU9ZngPF+atU0jm1tLq5LzGPdL2eOjFfrM9bebloK1ZqfUAA==
  template:
    metadata:
      name: oauth2-proxy-keycloak
      namespace: business
    type: Opaque
