---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-keycloak
  namespace: business
spec:
  encryptedData:
    client-secret: AgBxz67TAD/cC2vJ1GdS33S24ZaK7mVibSB2UbXD5NHqHoOzFcoivuBzEWBX6wtP077OhMLlZHsY3FdBYCdhP763FdQVEOAuc4kwOBgQIpJIv5RP597nJg/h8+jFHRMdJ0P4LumTOpfClraA1jQ6hkYs2gM9MSVWRG+de3MkKfiaYzJuKk0ujNUtgiPZUPNc0uyg0wLd5miTcvMuUoSYQs2Gp9CGwFiIKQUaFkNouZBsb3JWdTcEjQja60+dvV9aPDS+9BTOBiqwSoVBExCugJvlsbFDS9O6iz4OBRb6dqS86Hr95nD3Ib4K+gBQr0b0baTrFG+DZuSByx0ZMa57/JJ9IbKLlJUKNQaG4kt8yxmnahWi7gQ8OTBJg3E94dR5QJk9EZMdtm4cXenEjXYssG7OIWgZwns9IvKboPVFY1ANqZH2abiCfeV2tSLxVGngEAaeTpUBnXxeDpmJ79JboTPRHSuTHGThYTXRMKlD00LooHIvm9jOp6W8xaq29Bu7+fc9uwCTA6FFIlqs+S8XRw/cFfYWk2yQnZvMfcJINQN62fnIn3fYiv/UMuVoLFUbdrCW4YXpI/pH0VDTTKzPqTPZZo/D2TbrM1Af5QGFG70f2DE84CrJ4bdKTiuFu8sMG0dO7pG56KAIWOC4IoiEOZtZPcRPae4g5R4tpwRyktgIraNGsjDRzhhXUznGddhGSHvsQcfvpjMzcYmDGK0qWbgLAa5I0iz6y3KUX7omsCbrH9WW8xazue985xlXlDmm
    cookie-secret: AgB2FWvZJBagIPt1D5oCYHrTNbBebKgeExuYW7dTSv2vNDjCJO5OwkUMxooX0uVXptYVXyOxZ0ZB1A9bAwk3/xP0kFA2cVTfL8z2V3dkeHIsihSyP+8oTOTv3Y9Lyg116a1Nrwg89hNIQKIJ3LiziWrFZTwC/rcm6xQLEBppqNvZyEWwu7xRnbT+bj+74G9NycJm4OIK6xsJmwSASGbVRG55koj/xe7J0CFDXAX27LjZdW3+KSx9q7zPU5xZCG8EliJSMGVKCZ+P2Zw+9bkHBxLKaXLOMaJAsZyriYpe4Dc5AVq0KYGfs+/igXIuS5H79y+MtBu/8KwaU5yjpbuFxA/ccbLSpDRqhVVO4VrjREUnF50YTTrOzF26LZhSVvV8tn1ixTvJZrXuWDZ6oTMQEOHxrv2FBtZehsiuw2o4KlWkSaU0bodS/rhuMjwkPyffJQNoCwh4uNI2zgHJRALsUzYHwjiHwA9gPbp3nLvM9zhZSBLRab0AZM70qj9qP6fLpqwJJxoisXvDng7cL6mgZoFntZX2OFJUG7nWt36ez9Nu1ylIUfB6zd863Zupn4x0/ZcfT8epFhWF7/LQov0+0fN5TY+pPO6e0r0yRaUgXZe00dJQvYDnTi8nqTw/3xq16j8V1qW9bsQiw29PIGdHNBXwUTo/wx7lA03QOmeXF9YwJCDZJNbdtJcnCv2COXwhx1axJk2nNKRMjQGALgs33BZ3l50+qIY30eA6PKBoSG4xnQ==
  template:
    metadata:
      name: oauth2-proxy-keycloak
      namespace: business
    type: Opaque
