---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-keycloak
  namespace: business
spec:
  encryptedData:
    client-secret: AgBCVGJrpkEtx3MvkOBnCoaBbUZO7gMy63jlA6zsvnIOZxof1ubTR+RCeyuleXK9e5edro0wMU9ErAhnR+CFiyREkd1VpHoW9KhKSpAOO32+VJEz6YPESeu3zbUeprJJZUmJEMakWyMsM5/uUxzkgecAsuVfhqVKsAqVCBApkT+NpjH6vmtM8MrYqvYrjs5gt1fNw13JOqQzxOC4RsJOi5NupWaYJ2wtEMt5shktnyPjoXJ6tCHFLaA/JPXQIMREkOLhb8UZCeeiRL75lvxUiN4l7kvTi2thBQa+6FlJpUNCiu7FdAPVOayLzZH+YUfFIXggp7N+cy9CqBXVY8Dy1xdQbF5qsq6dldaVdN8iDyPSjQtF7S9Tqj0aTlt9GtwOSkCy9xTJ2oYTs41f9IrCgCzc/sL9ApD3FUiRdhLDkYFhuNLZxPJDlqkwatN4yMB8WSPRen5JAv44m/L6KPSCxp2L29sHKxr2aDyKXMOPZsiG+RJDMh6rIZBrpDw22Qpbyq5VqxfYUHPc8Y5ApMqn2llQTbFKn5B+4U2Y0l7+McF3avLi11/xu/scRgeFj6nJQborF15eun9IVMO1GeelzGF8qx3Qj3P0nl6CG4pYGnMIZ9at77N11yxrui/0EeZg5h3FOCnTqk1K3AwFqxXLLACatQ1R5U+fZKy1X2uXVCT+o3o4ZhtOjGbX5Mxi9T0oxekPYYSlp4AaeWNkd/FYhsDAdjW8/PMrvlkWYNMJ6K5Z++yHvlQaiewpO787Mg==
    cookie-secret: AgAfnPrgPiCPzmwcx1c4P3tNfEemXxEsPNx5Cw6LfKv8i04kUaV7WM6wQUEE1P1UuCmi3vjZMLLWeunPbCNQJEmSC/4zXlCkx/xyzbf7KogiTDVg0LMWcyrwMfTgS24UsDcru8gNfG/uNPtLUx7m7nZmh2us2nDoqfA+m3RDiE8OWKvnUn8m6tYhrFC3zF+g2CeGGqjS8ZJm+wlZHmMji5jQpacieyz/ziGgMWwWAes8PvMEKE6uK1ddyfMqjjnJ/iTRMeCwP0s3CH0ejA9OQzyFZmgGxYCvE9Ilys5a9TJ8Rvhvkb2XPg2hL9AndLoaQvrFCV6DzjBT0DXG+lRUpoa0YFay0ii3qr/aa158RhjZKcZr0tX+ngzUmkWMU5JXkmiB4OEKBtDUMcRHlw3svA1Z5Avr2ElRew9zlZs1JDtTtUFT3t3YlvT5NxMUJsfhAMoyzC2CUj4umycdrA4hRnxfrBAdMhl8r1IngNg3VTQ/wszbJrsJM2a/TvvvuiJgOAkUnskTTdfBifiZ5qRGIG0wfxCoq4711SBfPSY99yvOsGCHt23q+hMk+DJXtGdCcORycIYNRJd0aYcNzY5CtdGEKLuRxagZEYr0ptwXXMJ0rCLTwBde1t3BCPZxPvIF0WEBz303nDPN+eZGQADBs/rOqJDl6juGEk2X6zb9NHG7HHY6S76KiUdW2w90F9KmgROSh6xvaK04ARlWEBWIHF2YdH2K4Alz3RCRE7FrjZ6bfQ==
  template:
    metadata:
      name: oauth2-proxy-keycloak
      namespace: business
    type: Opaque
